# Generated by Django 3.2.10 on 2023-05-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicledb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(blank=True, max_length=100, null=True)),
                ('vtype', models.CharField(blank=True, max_length=100, null=True)),
                ('vmodel', models.IntegerField(blank=True, null=True)),
                ('vdescription', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
