# Generated by Django 3.2.10 on 2023-05-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_admindb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindb',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
